MathematicsWebsite/urls.py
from django.conf.urls import include , url
from django.contrib import admin

urlpatterns = [
    url(r'^calculator/', include('calculator.urls')),
    url(r'^$', include('calculator.urls')),
    url(r'^admin/', admin.site.urls),
]

calculator/urls.py
from django.conf.urls import url

from . import views

app_name = 'calculator'
urlpatterns = [
    url(r'^$', views.calculator, name='calculator'),
    url(r'^result/$', views.result, name='result'),
]

calculator/models.py
from django.db import models

# Create your models here.

calculator/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

# Create your views here.

def calculator(request):
	template = 'calculator/calculator.html'
	return render(request, template)

def result(request):
	template = 'calculator/result.html'
	value1 = int(request.GET['value1'])
	value2 = int(request.GET['value2'])
	ans = None
	if request.GET['operator'] == '+':
		ans = value1 + value2
	elif request.GET['operator'] == '-':
		ans = value1 - value2
	elif request.GET['operator'] == '*':
		ans = value1 * value2
	elif request.GET['operator'] == '/':
		ans = value1 / value2
	return render(request, template , {'answer':ans})

calculator/templates/calculator/calculator.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'calculator/style.css' %}" />

<h1>Calculator</h1>

<form action="{% url 'calculator:result' %}" method="get">
    Value 1
    <input type="text" name="value1"><br><br>
    Value 2
    <input type="text" name="value2"><br><br>
    <input type="submit" value="+" name="operator">
    <input type="submit" value="-" name="operator">
    <input type="submit" value="*" name="operator">
    <input type="submit" value="/" name="operator">
</form>

calculator/templates/calculator/result.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'calculator/style.css' %}" />

<h1>Answer = {{ answer }}</h1>

<form action="{% url 'calculator:calculator' %}" method="get">
    <input type="submit" value="back" name="back">
</form>